version: '3'


services:

  postgres:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: hava_jack
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg:/var/lib/postgresql/data