server:
  port: 8080

spring:
  application:
    name: hava-jack
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        jdbc.lob.non_contextual_creation: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/hava_jack
    username: postgres
    password: postgres